from typing import Tuple

class Vector2:
    x: float
    y: float

    def __init__(self, x: float, y: float): ...
    def copy(self) -> Vector2: ...
    def to_tuple(self) -> Tuple[float, float]: ...
    def __add__(self, other: Vector2) -> Vector2: ...
    def __sub__(self, other: Vector2) -> Vector2: ...
    def __mul__(self, other: Vector2 | float) -> Vector2: ...
    def __truediv__(self, other: Vector2 | float) -> Vector2: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
