class Vector2:
    x: float
    y: float

    def __init__(self, x: float, y: float): ...
    def copy(self) -> Vector2: ...
    def to_tuple(self) -> tuple: ...
    def __add(self, other: Vector2) -> Vector2: ...
    def __sub(self, other: Vector2) -> Vector2: ...
    def __mul(self, other) -> Vector2: ...
    def __truediv(self, other) -> Vector2: ...
    def __add__(self, other: Vector2): ...
    def __sub__(self, other: Vector2): ...
    def __mul__(self, other: Vector2 | float): ...
    def __truediv__(self, other: Vector2 | float): ...
    def __str__(self): ...
