class Vector2:
    x: float
    y: float

    def __init__(self, x: float, y: float): ...
    def copy(self) -> Vector2: ...
    def to_tuple(self) -> tuple[float, float]: ...
    def magnitude(self) -> float: ...
    def __add__(self, other: Vector2) -> Vector2: ...
    def __sub__(self, other: Vector2) -> Vector2: ...
    def __mul__(self, other: Vector2 | float) -> Vector2: ...
    def __truediv__(self, other: Vector2 | float) -> Vector2: ...
    def __neg__(self) -> Vector2: ...
    def __lt__(self, other: Vector2) -> bool: ...
    def __gt__(self, other: Vector2) -> bool: ...
    def __abs__(self) -> Vector2: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
