[build-system]
requires = ["scikit-build", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "extro"
version = "0.8.0a0"
description = "2d game engine with raylib as the backend"
authors = [{name="Landon Redmond"}]
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "raylib>=5.5.0.3"
]

[project.optional-dependencies]
dev = [
    "nanobind>=2.9.2",
]