[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "extro"
version = "0.6.0a0"
description = "2d game engine with raylib as the backend"
authors = [{name="Landon Redmond"}]
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "raylib>=5.5.0.3"
]

[project.optional-dependencies]
dev = [
    "Cython>=3.1.3",
    "cythonbuilder>=0.1.24",
    "setuptools>=80.9.0",
    "wheel",
]