[build-system]
requires = [
    "nanobind>=2.9.2",
    "scikit-build>=0.18.1",
    "setuptools>=80.9.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "extro"
version = "0.8.1-alpha"
description = "2D game engine with Raylib backend"
authors = [{ name = "Landon Redmond" }]
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "raylib>=5.5.0.3"
]

[tool.setuptools]
package-dir = { "" = "src" }
packages = [
    "extro",
    "extro.shared",
    "extro.internal.systems.Collision"
]
include-package-data = true
