from src.values.Vector2 import Vector2

class CollisionMask:
    position: Vector2
    size: Vector2
    rotation: float

    def __init__(self, position: Vector2, size: Vector2, rotation: float = 0): ...
    def get_vertices(self) -> list[object]: ...
    def get_axes(self) -> list[object]: ...
    def collides_with(self, other_collision_mask: CollisionMask) -> bool: ...
