from typing import overload


def from_degrees(degrees: float) -> Angle: ...

def from_radians(radians: float) -> Angle: ...

class Angle:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, radians: float) -> None: ...

    @property
    def radians(self) -> float: ...

    @radians.setter
    def radians(self, arg: float, /) -> None: ...

    @property
    def degrees(self) -> float: ...

    @degrees.setter
    def degrees(self, arg: float, /) -> None: ...

    def copy(self) -> Angle: ...

    def __add__(self, arg: Angle, /) -> Angle: ...

    def __sub__(self, arg: Angle, /) -> Angle: ...

    @overload
    def __mul__(self, arg: float, /) -> Angle: ...

    @overload
    def __mul__(self, arg: Angle, /) -> Angle: ...

    @overload
    def __truediv__(self, arg: float, /) -> Angle: ...

    @overload
    def __truediv__(self, arg: Angle, /) -> Angle: ...

    def __iadd__(self, arg: Angle, /) -> Angle: ...

    def __isub__(self, arg: Angle, /) -> Angle: ...

    def __imul__(self, arg: float, /) -> Angle: ...

    def __itruediv__(self, arg: float, /) -> Angle: ...

    def __eq__(self, arg: object, /) -> bool: ...

    def __ne__(self, arg: object, /) -> bool: ...

    def __lt__(self, arg: Angle, /) -> bool: ...

    def __le__(self, arg: Angle, /) -> bool: ...

    def __gt__(self, arg: Angle, /) -> bool: ...

    def __ge__(self, arg: Angle, /) -> bool: ...

    def __neg__(self) -> Angle: ...

    def __repr__(self) -> str: ...
