from typing import overload


class RGBAColor:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...

    @property
    def r(self) -> int: ...

    @r.setter
    def r(self, arg: int, /) -> None: ...

    @property
    def g(self) -> int: ...

    @g.setter
    def g(self, arg: int, /) -> None: ...

    @property
    def b(self) -> int: ...

    @b.setter
    def b(self, arg: int, /) -> None: ...

    @property
    def a(self) -> int: ...

    @a.setter
    def a(self, arg: int, /) -> None: ...

    def to_tuple(self) -> tuple: ...

    def __repr__(self) -> str: ...
