from typing import overload


class Vector2:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, x: float, y: float) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    def magnitude(self) -> float: ...

    def dot(self, other: Vector2) -> float: ...

    def to_tuple(self) -> tuple: ...

    def copy(self) -> Vector2: ...
