

def create_collision_mask(id: int, size: "Vector2", position: "Vector2", rotation: "Angle") -> None: ...

def destroy_collision_mask(id: int) -> None: ...

def check_collisions(valid_collision_masks: dict, updated_collision_masks: list) -> list: ...
