

def compute_vertices(size_x: float, size_y: float, position_x: float, position_y: float, rotation: float) -> list: ...

def compute_axes(vertices: list) -> list: ...

def does_collide(instance1_vertices: list, instance1_axes: list, instance1_position: tuple, instance2_vertices: list, instance2_axes: list, instance2_position: tuple) -> tuple: ...
