

def create_collision_mask(instance_id: int, size: "Vector2", position: "Vector2", rotation: float) -> None: ...

def destroy_collision_mask(instance_id: int) -> None: ...

def check_collisions(arg: list, /) -> list: ...
