

def solve_impulse(normal: "Vector2", contact_point: "Vector2", restitution: float, total_inverse_mass: float, instance1_bounding: list, instance1_velocity: "Vector2", is_instance1_dynamic: bool, instance1_rotational_velocity: float, instance1_mass: float, instance2_bounding: list, instance2_velocity: "Vector2", is_instance2_dynamic: bool, instance2_rotational_velocity: float, instance2_mass: float) -> tuple: ...

def set_impulse_scaler(scaler: float) -> None: ...
