

def create_physics_body(id: int, size: "Vector2", position: "Vector2", rotation: "Angle", velocity: "Vector2", angular_velocity: "Angle") -> None: ...

def destroy_physics_body(id: int) -> None: ...

def step(physics_body_updates: list) -> None: ...

def resolve_collisions(collisions: list) -> list: ...

def set_impulse_scaler(scaler: float) -> None: ...
