from extro.shared.Vector2 import Vector2

def register(instance_id: int) -> None: ...
def unregister(instance_id: int) -> None: ...
def update() -> None: ...
def resolve_collisions(collisions: list[tuple[int, int]], collision_data: dict[tuple[int, int], tuple[Vector2, float]]) -> None: ...
