from extro.shared.Vector2 import Vector2

class CollisionMask:
    vertices: list[Vector2]
    axes: list[Vector2]

    def __init__(self, position: Vector2, size: Vector2, rotation: float = 0): ...
    def collides_with(self, other_collision_mask: CollisionMask) -> bool: ...
    @property
    def position(self) -> Vector2: ...
    @position.setter
    def position(self, position: Vector2): ...
    @property
    def size(self) -> Vector2: ...
    @size.setter
    def size(self, size: Vector2): ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, rotation: float): ...
